---
proj_root:
  local: '~/querysum'
  afs: '~/querysum'

proj_paths:
  data: 'data/'
  squad: 'squad/'
  docs: 'docs/'
  topics: 'topics/'

  summary_results: 'summary_results/'
  summary_refs: 'summary_refs/'
  summary_targets: 'summary_targets/'

  # dataset
  dataset: 'dataset/'
  train: 'train/'
  dev: 'dev/'
  test: 'test/'

  # res
  res: 'res/'
  performances: 'perf/'
  log: 'log/'
  model: 'model/'

  # predictions
  pred: 'pred/'
  graph: 'graph/'
  sim_mat: 'sim_mat/'
  rel_vec: 'rel_vec/'
  sid2abs: 'sid2abs/'
  sid2score: 'sid2score/'

  rank: 'rank/'
  text: 'text/'
  rouge: 'rouge/'
